flybywiresim/installer

- src/components/AircraftSection/index.tsx
- src/components/AircraftSection/styles.tsx
> Changed Text | Resized Version Box

- src/components/AircraftSection/index.tsx
> Added cancel download option

- README.md
> Correct logo in README

- .eslintrc.json
- .github/workflows/master.yaml
- .github/workflows/pr.yaml
- .github/workflows/release.yaml
- package-lock.json
- package.json
- src/main/index.ts
- src/renderer/actions/install-path.utils.tsx
- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/AircraftSection/styles.tsx
- src/renderer/components/GeneralSettings/index.tsx
- src/renderer/components/HomeSection/index.tsx
- src/renderer/redux/actionTypes/index.ts
- src/renderer/redux/actions/downloads.actions.ts
- src/renderer/redux/reducers/downloads.reducer.ts
- src/renderer/redux/reducers/index.ts
- src/renderer/redux/store.ts
- src/renderer/redux/types.ts
- src/renderer/renderer.tsx
> Add CI/CD pipeline

- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/AircraftSection/styles.tsx
Fixes #18 
* Prevent accidentally modifying installation if the current install is a symlink to a `git` repo
> feat: prevent overriding git-based install

- src/renderer/components/AircraftSection/styles.tsx
- src/renderer/components/HomeSection/styles.tsx
> Background Changes

- src/renderer/components/AircraftSection/styles.tsx
- src/renderer/components/HomeSection/styles.tsx
> Background images

- src/renderer/components/AircraftSection/VersionHistory.tsx
- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/AircraftSection/styles.tsx
- src/renderer/components/App/GitHubApi.ts
- src/renderer/components/App/index.tsx
- src/renderer/index.css
Fixes part of #25
* Adds "Version history" section to aircraft page
Figma
> feat: add version history

- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/AircraftSection/styles.tsx
Fixes #13 
I added a install button which says "Please Close MSFS" 
also made the install bar smoother.
> feat: checks if msfs is open

- src/renderer/components/AircraftSection/index.tsx
Fixes #41
Checks if build_info.json is changed
Discord username (if different from GitHub): Falcon#5815
> feat: Checks if build_info.json is changed

- .github/workflows/commit.yaml
- .github/workflows/master.yaml
- .github/workflows/release.yaml
- package.json
Add release workflow step to push the installer to a CDN
Organization-wide secrets have been set up
> build: CDN distribution

- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/AircraftSection/styles.tsx
> feat: git exclusion

- .github/workflows/master.yaml
- .github/workflows/release.yaml
> distribute exe instead of zip

- src/main/index.ts
- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/AircraftSection/styles.tsx
- src/renderer/components/App/index.tsx
- src/renderer/components/GeneralSettings/index.tsx
- src/renderer/style/theme.ts
- src/renderer/utils/DataCache.ts
> fix: misc improvements and corrections

- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/AircraftSection/styles.tsx
- src/renderer/components/Logo/index.tsx
- src/renderer/components/Logo/styles.tsx
- src/renderer/components/LogoWithText/index.tsx
- src/renderer/style/theme.ts
Fixes #84
- Added Switch version button
- Added Disabled functionality when msfs is running
Switch button:
Disabled functionality:
> feat: add Switch version and disable button when msfs is running

- src/renderer/components/AircraftSection/index.tsx
Fixes #90
By default assume msfs is running, until process check says different
> fix: prevent the user from installing an update while msfs is open

- src/renderer/components/App/index.tsx
Partial #89
- Moved Stable version to the far left
- New order Stable -> Development -> Experimental
> feat: change version order

- src/renderer/components/AircraftSection/index.tsx
- Replaced `Please close MSFS` with `Checking status...` on page entry until the PID status of MSFS has been checked.
> feat: checking status on page entry

- .github/workflows/master.yaml
- .github/workflows/release.yaml
- package.json
Rename the setup of the installer to setup.exe
> fix: setup renamed from installer to setup

- .github/CHANGELOG.md
Create changelog for future usage
If you feel like your commit needs better declaration or should be included, but it isn't now, feel free to request changes.
> feat: create changelog

- src/renderer/components/App/index.tsx
> refactor: changed cdn links to the bunnycdn links

- .github/CHANGELOG.md
- .github/WARNING_EXPERIMENTAL_A32NX_AP.md
- .github/WARNING_EXPERIMENTAL_A32NX_FBW.md
- src/renderer/components/AircraftSection/TrackSelector.tsx
- src/renderer/components/App/index.tsx
- src/renderer/components/ChangelogModal/styles.tsx
- src/renderer/components/WarningModal/index.tsx
- src/renderer/components/WarningModal/styles.tsx
- src/renderer/redux/reducers/index.ts
- src/renderer/redux/reducers/warning.reducer.ts
- Implement download for 'Custom FBW+AP'
- Add warning message when selecting experimental version
> feat: implement warning message on download with experimental versions (also added cfbw+ap)

- src/renderer/components/GeneralSettings/index.tsx
- src/renderer/components/GeneralSettings/styles.tsx
Fixes #100 
Made reset button more clear of its actions
Before:
After:
> feat: made reset button more clear of its purpose

- src/renderer/components/AircraftSection/TrackSelector.tsx
Changed the unselected color to dark grey.
Before:
After:
> feat: new branch selector colors

- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/App/index.tsx
- src/renderer/components/WarningModal/index.tsx
- src/renderer/components/WarningModal/styles.tsx
- src/renderer/index.css
- src/renderer/redux/actionTypes/index.ts
- src/renderer/redux/actions/warningModal.actions.ts
- src/renderer/redux/reducers/index.ts
- src/renderer/redux/reducers/warningModal.reducer.ts
- src/renderer/redux/types.ts
> feat: added warning modal

- .github/CHANGELOG.md
> docs: Update Changelog

- src/renderer/components/WarningModal/styles.tsx
- Moved the title down a bit
- changed link color to blue instead of dark gray
Before
After
> fix: Warning Modal styling

- src/renderer/components/AircraftSection/index.tsx
- Do not allow version switching while download preparation
- Show Switch Version instead of Update
> fix: switch version

- .github/CHANGELOG.md
- src/renderer/components/App/index.tsx
- remove custom autopilot temporarily (on request by @aguther )
> remove custom autopilot temporarily

- src/renderer/components/InstallerUpdate/styles.tsx
> fix: installer update note

- package-lock.json
- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/App/index.tsx
> feat: added branch descriptions

- src/renderer/components/GeneralSettings/index.tsx
- src/renderer/components/WarningModal/index.tsx
- src/renderer/components/WarningModal/styles.tsx
Added a checkbox to disable the warning modal
- Modal immediately disappears after clicking checkbox
> feat: warning modal now able to be disabled

- src/main/index.ts
- src/renderer/components/ChangelogModal/index.tsx
- src/renderer/components/ChangelogModal/styles.tsx
- src/renderer/components/GeneralSettings/index.tsx
Fixes #119 
automatically display changelog after update
> feat: automatically display changelog after update

- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/ChangelogModal/index.tsx
- src/renderer/components/GeneralSettings/index.tsx
- src/renderer/redux/reducers/changelog.reducer.ts
- src/renderer/redux/reducers/index.ts
- src/renderer/redux/types.ts
> refactor: redux state names

- .github/workflows/pre-release.yaml
Push a pre-release to GH when using an `-rc` tag.
N/A
N/A
> build: add pre-release workflow

- src/main/index.ts
> fix: first time selecting an experimental version does not work due to undefined value in store

- .github/CHANGELOG.md
> docs: clean up changelog

- package-lock.json
- package.json
> chore: bump fragmenter version

- .github/CHANGELOG.md
- package.json
> chore: bump version

- package-lock.json
- package.json
- src/main/index.ts
- src/renderer/components/AircraftSection/index.tsx
> feat: increased logging

- scripts/cdn.sh
Change the CDN upload URL
N/A
N/A
> build: change cdn upload URL

- package-lock.json
- package.json
Add retry logic for network errors and not just CRC issues.
https://github.com/flybywiresim/fragmenter/commit/aed58c4356dbec93aec1c37ae1c1479b32db3960
> chore: update fragmenter

- src/renderer/components/AircraftSection/TrackSelector.tsx
- src/renderer/components/AircraftSection/index.css
- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/App/SideBar.tsx
* Re-introduce `isInstalled` color
* Refactor track selection to remove use of connected props, styled components
> refactor: track selection

- src/renderer/components/AircraftSection/index.tsx
* Fixed title text for branch description in `AircraftSelection`
> fix(AircraftSelection): fix title for branch desc

- .github/CHANGELOG.md
- src/renderer/components/AircraftSection/index.tsx
- src/renderer/utils/Directories.ts
* Introduce `Directories` utility to avoid repetitive concatenations and settings fetches
> refactor: introduce Directories utility

- package-lock.json
- package.json
- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/App/SideBar.tsx
- src/renderer/redux/actions/downloads.actions.ts
- src/renderer/redux/reducers/downloads.reducer.ts
- src/renderer/redux/types.ts
Make use of the new install events introduced in fragmenter v0.3.0
N/A
N/A
> feat: fragmenter events

- src/renderer/components/App/index.tsx
* Replaces Custom FBW (`fbw` branch) with Experimental (`autopilot` branch)
> feat: replace Custom FBW with new Experimental

- src/renderer/components/AircraftSection/TrackSelector.tsx
- src/renderer/components/AircraftSection/VersionHistory.tsx
- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/App/SideBar.tsx
- src/renderer/components/App/index.tsx
- src/renderer/components/App/styles.tsx
- src/renderer/components/WarningModal/index.tsx
- src/renderer/data.tsx
- src/renderer/redux/actions/warningModal.actions.ts
- src/renderer/redux/reducers/installedTrack.reducer.ts
- src/renderer/redux/reducers/selectedTrack.reducer.ts
- src/renderer/redux/store.ts
- src/renderer/redux/types.ts
- src/renderer/renderer.tsx
- src/renderer/utils/InstallerConfiguration.ts
> feat: introduce configuration infra

- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/AircraftSection/styles.tsx
- src/renderer/components/App/index.tsx
- src/renderer/data.tsx
- src/renderer/utils/InstallerConfiguration.ts
* Remove variants to handle them in fragmenter metadata
> refactor: remove variants

- src/renderer/components/App/SideBar.tsx
* Fix sidebar update icon not being yellow
> fix: wrong color on sidebar update icon

- src/renderer/components/AircraftSection/index.tsx
- src/renderer/utils/Directories.ts
- src/renderer/utils/Msfs.ts
Add utilities for:
- Installation detection
- Installation cleanup
- MSFS detection
N/A
N/A
> refactor: more utility functions

- src/renderer/components/AircraftSection/styles.tsx
- src/renderer/components/App/SideBar.tsx
- src/renderer/components/App/index.tsx
- src/renderer/components/App/styles.tsx
- src/renderer/components/ChangelogModal/styles.tsx
- src/renderer/components/InstallerUpdate/styles.tsx
- src/renderer/components/Logo/index.tsx
- src/renderer/components/Logo/styles.tsx
- src/renderer/components/SettingsSection/index.tsx
- src/renderer/components/SettingsSection/styles.tsx
- src/renderer/components/WarningModal/styles.tsx
- src/renderer/index.css
- src/renderer/style/App.scss
- src/renderer/style/theme.ts
*   fix warning modal
*   fix changelog modal
*   fix scrollbar
*   fix background
*   fix settings menu
*   re-add title
*   fix progress line
*   fix installer update badge
> feat: design fixes

- package-lock.json
- package.json
Updated Fragmenter to send query params `forcedBust` and `retry` to better logging of retries and users disabling the CDN.
> feat: include more query params for logging

- src/renderer/components/AircraftSection/index.tsx
* Change progress bar color to teal to better match new theme
> fix: use teal for progress indicator

- .github/CHANGELOG.md
> fix: Update CHANGELOG.md

- package-lock.json
- package.json
When switching between versions and all modules need to be updated fragmenter now performs a full install.
> feat: perform full install when all modules change

- src/renderer/components/App/SideBar.tsx
- tailwind.config.js
* Adds spin animation on sidebar update icon
> feat(sidebar): add spin on update icon

- .github/CHANGELOG.md
- src/renderer/components/AircraftSection/index.tsx
- src/renderer/renderer.tsx
- src/renderer/utils/Directories.ts
Fixes #208
- Remove all temp directories on startup
- Remove all temp directories on close via window buttons
> feat: cleanup of old temp directories on startup and exit

- src/renderer/components/AircraftSection/index.tsx
* Increase font size on `AircraftSelection` description
> ui(aircraft-selection): improve description font size

- src/renderer/components/AircraftSection/index.tsx
- src/renderer/data.tsx
- src/renderer/utils/InstallerConfiguration.ts
change autopilot branch to experimental
introduce alternative URLs
> fix: change cfbw-cap/autopilot to experimental

- package-lock.json
- package.json
- src/renderer/components/GeneralSettings/index.tsx
- tailwind.config.js
- change checkmarks to toggles in settings
- enable CSS purging
Before:
After:
> feat(settings):  toggle not checkmark

- src/renderer/components/AircraftSection/LiveryConversion/index.tsx
- tailwind.config.js
* Add conversion percentage to LCU dialog
> feat(lcu): add conversion progress percentage

- src/renderer/components/AircraftSection/LiveryConversion/index.tsx
> fix(lcu): numbers with decimal too wide

- src/renderer/components/GeneralSettings/index.tsx
-v infront of version number in settings ("1.2.0" -> "v1.2.0")
> fix(settings): add v to version number

- src/renderer/components/App/SideBar.tsx
> fix: wrong status in sidebar

- src/renderer/components/GeneralSettings/index.tsx
- change setting name "Use CDN" to "Use CDN Cache"
> fix: "Use CDN" -> "Use CDN Cache"

- package-lock.json
- src/renderer/components/AircraftSection/LiveryConversion/index.tsx
- src/renderer/utils/LiveryConversion.ts
* Remove converted livery packages if conversion fails
> fix(lcu): remove failed conversion packages

- package-lock.json
- package.json
> chore: update react components

- src/renderer/data.tsx
> fix: rename help -> support

- src/renderer/renderer.tsx
Rename #help to #support
Discord username (if different from GitHub): SjotgunSjonnie#9623
> chore: rename #help to #support

- .github/CHANGELOG.md
- package-lock.json
- package.json
- src/main/index.ts
Fixes #282
Check, whether values to be stored are undefined.
> fix(settings): prevent storing undefined value during first launch

- README.md
- package-lock.json
- package.json
- src/main/index.ts
Use `concurrently` to run webpack in watch-mode and electron at the same time.
> build: add watch mode for development

- src/renderer/components/App/styles.tsx
- src/renderer/style/theme.ts
Removed unused code.
No visual changes.
> refactor: remove unused code

- .github/CHANGELOG.md
- src/main/index.ts
- src/renderer/components/AircraftSection/index.tsx
Shows a taskbar progress bar during installation.
Discord username (if different from GitHub): Erick [Z-6]#6484
> feat: show taskbar progress bar during installation

- .github/CHANGELOG.md
- package-lock.json
- package.json
- src/common/settings.ts
- src/renderer/components/ErrorModal/index.tsx
> fix: error during configuration of community directory

- src/renderer/components/AircraftSection/index.tsx
- src/renderer/utils/Directories.ts
> feat: add uninstall button

- .github/CHANGELOG.md
- src/renderer/data.tsx
Re-enables A32NX experimental version.
> feat: re-enable exp

- src/renderer/components/AircraftSection/index.tsx
- src/renderer/data.ts
- src/renderer/redux/features/downloads.ts
- src/renderer/redux/types.ts
fixes not being able to cancel any other than the last started download
> fix: separate abortControllers for each download

- src/renderer/components/AircraftSection/TrackSelector.tsx
- src/renderer/components/AircraftSection/index.tsx
- src/renderer/components/App/AddonBar.tsx
- src/renderer/components/App/NavBar.tsx
- src/renderer/components/SettingsSection/index.tsx
- src/renderer/components/SideBar/index.tsx
- src/renderer/data.ts
- tailwind.config.js
Fixed/re-edit/redo some of the theme design for the installer
Discord username (if different from GitHub): GhostEagle68#0030
> feat: some theme fixes

- src/renderer/components/AddonSection/index.tsx
- src/renderer/components/App/AddonBar.tsx
- src/renderer/components/App/index.tsx
- fixes invalid previously stored lastShownSection values
- renames aircraft-section links to addon-section
> fix: invalid lastShownSection

- .eslintrc.json
- src/common/channels.ts
- src/common/settings.ts
- src/main/index.ts
- src/renderer/actions/install-path.utils.tsx
- src/renderer/components/AddonSection/HiddenAddonCover/HiddenAddonCover.tsx
- src/renderer/components/AddonSection/MainActionButton.tsx
- src/renderer/components/AddonSection/ReleaseNotes/index.tsx
- src/renderer/components/AddonSection/index.tsx
- src/renderer/components/App/SideBar.tsx
- src/renderer/components/App/index.tsx
- src/renderer/components/Modal/index.tsx
- src/renderer/components/SettingsSection/index.tsx
- src/renderer/data.ts
- src/renderer/index.tsx
- src/renderer/redux/features/applicationStatus.ts
- src/renderer/redux/features/configuration.ts
- src/renderer/redux/features/downloads.ts
- src/renderer/redux/features/installStatus.ts
- src/renderer/redux/features/releaseNotes.ts
- src/renderer/redux/features/selectedTrack.ts
- src/renderer/redux/store.ts
- src/renderer/style/theme.ts
- src/renderer/utils/AddonData.ts
- src/renderer/utils/LiveryConversion.ts
- require trailing comma on multiline objects
https://github.com/airbnb/javascript#commas--dangling
> refactor: require trailing comma on multiline objects

- src/renderer/data.ts
see [#7602](https://github.com/flybywiresim/a32nx/pull/7062)
> feat: recognise the correct version of external downloads

- src/renderer/components/App/index.tsx
Added status bar warning when using a non-production config
Discord username (if different from GitHub): Cdr_Maverick#6475
> feat: Added status bar warning when using a non-production config

- .github/workflows/master.yaml
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
- scripts/cdn-cf.sh
* Add CloudFlare CDN upload script
* Add CloudFlare CDN upload for release, pre-release and master upload pipelines
> ci: add cloudflare cdn upload

- src/renderer/utils/InstallManager.tsx
Avoids error in log when list is undefined or empty. 
Discord username (if different from GitHub): Cdr_Maverick#6475
> fix: Added check if incomp addons list is undefined or empty

- .github/workflows/master.yaml
- .github/workflows/pr-title.yml
- .github/workflows/pr.yaml
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
- upgrade GitHub Actions runner from ubuntu-18.04 to ubuntu-22.04
- Note: as the PR / title workflow requires the GitHub token and therefore relies on pull_request_target, the workflow runs off the master branch. Thus runs on this PR will not be affected by the changes. This run will never exit the queued status.
foxtrotsierra
> ci: upgrade GitHub Actions runner

- .github/workflows/master.yaml
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
- adds missing i386 install fix to remaining workflows ( see #436 )
foxtrotsierra
> ci: fix i386 install

- src/renderer/components/Modal/ErrorDialog.tsx
- change Discord support URL on Error Dialogs from [#a32nx-support](https://discord.com/channels/738864299392630914/785976111875751956) to [#installer-support](https://discord.com/channels/738864299392630914/1065394439608078336)
> feat: change discord support URL

- src/renderer/components/Modal/ErrorDialog.tsx
Correct support message to what's actually asked for on discord.
Discord username (if different from GitHub): slein15
> feat: Correct support info

- .github/CHANGELOG.yaml
- src/common/channels.ts
- src/main/index.ts
- src/renderer/actions/install-path.utils.tsx
- src/renderer/components/AddonSection/MyInstall/index.tsx
- src/renderer/components/ErrorModal/index.tsx
- src/renderer/components/SettingsSection/index.tsx
- src/renderer/rendererSettings.ts
- src/renderer/utils/Directories.ts
- src/renderer/utils/InstallManager.tsx
Fixes #417 
- in case both Microsoft Store Edition and Steam Edition are installed, the installer will prompt to select which one to manage
- in case no MSFS installation could be detected, it lets the user look up the correct path manually
- the MSFS base path is now stored to allow permanent handling of custom locations
- fixes work folder button in about page always opens Path for Steam Edition, thus not compatible with MS Store Edition ->Directories.inPackageCache()
- fixes openPath() does not focus Explorer window
(buttons for MS Store Editon or Steam Edition are only shown in case the respective expected path exists, when no installation is found, the user is automatically prompted to select a custom directory)
- Someone who is using the actual MSFS Steam Edition, please verify the …
> feat: improve MSFS base path detection

- package-lock.json
- package.json
Fixes https://github.com/flybywiresim/simbridge/issues/125
Same change was made in simbridge as it uses the same library to get the list of printers
> fix: pin pdf-to-printer version to fix selection

- .github/CHANGELOG.yaml
> chore: add missing v3.4.2 changelog

- .github/CHANGELOG.yaml
- package.json
- src/main/index.ts
- src/renderer/data.ts
- changes installer config URL to Cloudflare R2
- changes installer update URL to Cloudflare R2
> chore: change installer configuration and update URL to Cloudflare

- src/main/index.ts
Change is already live on v3.4
Can be removed as soon as we stop uploading the installer to Bunny
> fix: move people to new installer config url

- .github/CHANGELOG.yaml
Updates CHANGELOG in preparation for v3.4.4
> chore: Update to CHANGELOG in prep for v3.4.4

- .github/workflows/pr.yaml
- It's in the name
foxtrotsierra
> chore: upgrade actions/upload-artifact version
