flybywiresim/installer

src/renderer/components/AircraftSection/index.tsx

Fixes #20 
Use our statistics service for all downloads. The service sends a 302 with the correct URL. The download itself is not done through this service and still uses the CDN.
Service is running and tested. It only allows and counts URLs prefixed with `https://flybywiresim-packages.nyc3.cdn.digitaloceanspaces.com`

Use API for download statistics

---

src/renderer/components/AircraftSection/index.tsx

Fixes #29
Deletes the a32nx folder before unzipping the new installed file. 

Now deletes folder before unzipping new file

---

.github/CHANGELOG.md
src/renderer/components/AircraftSection/index.tsx

Fixes #79
Windows Notification is displayed when the download and install process is completed.
Currently there is no option to disable it, as considered in #79, but since it just goes away after some seconds (it's not permanent in notification center), I don't really see the need.
About the icon: there isn't really much we can do about it. It's using the partly transparent icon from the application and adds the windows theme color as a layer below it. Hopefully gets fixed in future Windows versions, just like in the start menu.

feat: add windows notification when download complete

---

.github/CHANGELOG.md
src/renderer/components/GeneralSettings/index.tsx
src/renderer/components/GeneralSettings/styles.tsx

Fixes #97 
- buttons now hover dark
- removed Modify button, as it was styled and positioned awkwardly. Functionality is now kept by the install folder declaration.
- refactor code
Before
After

fix: button styling in settings menu

---

.github/CHANGELOG.md
src/renderer/components/WindowActionButtons/index.tsx

Co-Authored-By: ZigTag <17077422+ZigTag@users.noreply.github.com>
Fixes #108 
We added a report issue button at the top right corner of the installer, the button will open the A32NX issue report page on GitHub.
Discord username (if different from GitHub): Arman#5297

feat: added issue creation button

---

src/renderer/components/AircraftSection/TrackSelector.tsx
src/renderer/components/AircraftSection/index.tsx
src/renderer/style/theme.ts

Fixes #57 
Updates the hover/active apperances of the version selection. This is an alternative/updated suggestion to PR #111 
(Framerate of gif is a bit low)
Not sure if the aircraft selection A32NX/A380X requires the same for now.
Discord username (if different from GitHub): Th3Alchemist#2043

Updates active/hover appearance

---

.github/CHANGELOG.md
src/renderer/index.css

I changed the color of the scrollbar for eased visibility.
**BEFORE**
**AFTER**
Ignore report button
Discord username (if different from GitHub):Arman#5297

fix: changed scrollbar color

---

src/renderer/components/WindowActionButtons/styles.tsx

Fixes #87
Made the menu buttons bigger
Before:
After:

feat: made the window buttons larger

---

LICENSE
package.json

As discussed a few months ago, the installer was supposed to be GPLv3 but was made MIT. Therefore all core contributors had already agreed with GPLv3, and only external contributors need to give additional consent. 

docs: switch to GPLv3

---

src/renderer/components/App/styles.tsx
src/renderer/components/WarningModal/styles.tsx

Removes the weird orange outline that I don't even know why it existed in the first place since the template should normally not have that...
Edit: removes it for other buttons as well, no idea how the issue was introduced tho
BEFORE

fix: buttons having a weird orange outline

---

src/renderer/components/AircraftSection/index.tsx

Fix cleanup of temporary directory when aborting a download
N/A
N/A

fix: no cleanup after abort

---

src/main/index.ts
src/renderer/components/App/index.tsx
src/renderer/components/App/styles.tsx
src/renderer/renderer.tsx

Fixes #50 
- minimum width now 1050 instead of 1000 (necessary due to added cfbw+ap button)
- window is now always centered on start
- window is now maximized on start, if it was maximized last time
- window is now resizable from top and top-left

fix: window size

---

src/main/index.ts
src/renderer/components/GeneralSettings/index.tsx

- After reset, the installer version was not displayed anymore until a restart. Fixed.

fix: reset version being 'lost' on reset

---

src/renderer/components/AircraftSection/index.tsx

change tempdir to '%temp%/flybywire_installer'
**!Important to prevent loading issues with MSFS**
(No, '%temp%/flybywire/current_install' does not work somehow, no clue why path.join() fails in all variants to do so)

change tempdir to OS default

---

.github/workflows/release.yaml
package.json
scripts/cdn.sh
src/main/index.ts

Upload releases to the new CDN. Keep old CDN for a single release to keep backward compatibility.
N/A
N/A

build: use new CDN for installer distribution

---

src/renderer/components/AircraftSection/TrackSelector.tsx
src/renderer/components/AircraftSection/index.tsx
src/renderer/components/App/index.tsx
src/renderer/redux/actionTypes/index.ts
src/renderer/redux/reducers/index.ts
src/renderer/redux/reducers/latestVersionNames.reducer.ts
src/renderer/redux/types.ts

* Use redux for storing state of latest mod track latest versions
* In a future PR: Use redux to store state of version history

refactor: use redux for track latest versions

---

src/renderer/components/AircraftSection/index.tsx
src/renderer/components/App/index.tsx

Install directory will be renamed from `A32NX`  to `flybywire-aircraft-a320-neo`. Both variants need to be supported.
N/A
N/A
Do not use the experimental version since the CDN purge isn't done automatically for that version yet.
1. Have an existing install called `A32NX`
2. Update/Change Version
- `A32NX` directory should get replaced by updated `flybywire-aircraft-a320-neo` directory
3. Update/Change Version
- `flybywire-aircraft-a320-neo` should stay but get updated
4. Remove `flybywire-aircraft-a320-neo` directory
5. Install Dev or Stable
- `flybywire-aircraft-a320-neo` is back
6. Test basic addon functionality in sim

feat: support alternative package names

---

src/renderer/components/App/index.tsx

Reduce the cache timeout to 5 minutes.
N/A
N/A

fix: reduce cache timeout for release info

---

src/renderer/components/AircraftSection/index.tsx

Disable the cancel button while decompressing to prevent a non-atomic filesystem action.
N/A

fix: disable cancel button while decompressing

---

package-lock.json
src/renderer/components/AircraftSection/index.tsx
src/renderer/components/App/index.tsx

Do not copy alternative directories and installs without `install.json` and just let them be deleted.
N/A
N/A

fix: only copy fragmenter installs to the temp directory

---

package-lock.json
package.json
src/main/index.ts
src/renderer/components/AircraftSection/index.tsx
src/renderer/components/GeneralSettings/index.tsx
src/renderer/redux/actions/downloads.actions.ts
src/renderer/redux/reducers/downloads.reducer.ts
src/renderer/redux/types.ts

- Allow users to disable the CDN by cache-busting.
- Fragmenter retries after an invalid CRC and automatically uses cache-busting after the first failure.

feat: cache busting and exponential backoff

---

src/main/index.ts
src/renderer/renderer.tsx

Fixes #196
* Introduce error screen which displays a stack trace and error message when a configuration could not be loaded

feat: introduce error screen

---

package-lock.json
package.json
src/renderer/components/AircraftSection/index.tsx

Send the module- and full-hash of the target version as query params in fragmenter. To always get the newest module-info a permanent cache-busting is enabled for the manifest request, which is only 2kB in size. This will act as an automatic cache-busting in case the automatic purge didn't work on bunny.net. The module cache-rate will not be affected since the hashes are the same for everyone and this is only a fallback to the existing purging.
N/A

feat: fragmenter hashes in query params

---

src/renderer/components/AircraftSection/TrackSelector.tsx
src/renderer/components/App/index.tsx
src/renderer/data.tsx
src/renderer/redux/actionTypes/index.ts
src/renderer/redux/reducers/latestVersionNames.reducer.ts
src/renderer/redux/types.ts
src/renderer/utils/AddonData.ts
src/renderer/utils/InstallerConfiguration.ts
src/renderer/utils/Msfs.ts

* Change `Configuration` data model to include information on track release model (released or rolling)
* Introduce `ModData` utility for getting additional mod data, including latest releases
* Refactor Redux latest version state to include release date and changelog URL (not yet used)

refactor: improve last release info, introduce AddonData

---

.github/workflows/release.yaml

Fixes #162
Remove DigitalOcean CDN as we do not support it any longer.

build: remove old cdn

---

src/main/index.ts
src/renderer/actions/install-path.utils.tsx
src/renderer/components/AircraftSection/LiveryConversion/index.tsx
src/renderer/components/AircraftSection/index.tsx
src/renderer/components/GeneralSettings/index.tsx
src/renderer/settings/index.ts
src/renderer/utils/Directories.ts
src/renderer/utils/LiveryConversion.ts

- add option to have a separate liveries directory
- livery conversion dialog now updates on any affecting settings

feat: separate liveries directory

---

src/renderer/components/GeneralSettings/index.tsx

- disabled livery conversion ignored in some cases
- changelog shown next restart after reset

fix: disabled livery conversion ignored, changelog shown after reset

---

.github/CHANGELOG.md
.gitignore
package-lock.json
package.json
scripts/licenses.js
src/renderer/components/DebugSection/index.tsx
src/renderer/components/GeneralSettings/index.tsx
src/renderer/components/GeneralSettings/styles.tsx

- Added a script to generate markdown files that contains all licenses.
- The script exits early during development when possible to save time.
- The markdown file can be opened through the settings page.
- It will open in your default `.md`-editor or ask you to pick an editor
- I tried embedding it but the rendering of the 47000+ lines takes about 3 seconds on my system. The UI freezes meanwhile -> Solution: open external
- The file can only be opened in `electron-builder` builds since it is located in the additional resources.
- Added a way to send arbitrary ipc-messages from the renderer to the main process through the debug menu.

feat: ship 3rd-party licenses with the installer

---

src/renderer/components/App/AddonBar.tsx

Fixed a bug where the install status animation would reset when the store was updated and the `AddonBarItem` component was subsequently re-rendered.
https://user-images.githubusercontent.com/19419678/150696895-894b81f0-2cae-4239-9a3c-2c447dcad153.mp4
https://user-images.githubusercontent.com/19419678/150696902-78a84e5b-e473-464d-8e86-83cb51624351.mp4
Discord username (if different from GitHub): MikeRoma # 0001

fix: install status animation restarting

---

src/common/channels.ts
src/main/index.ts
src/renderer/components/AircraftSection/index.tsx
src/renderer/components/App/index.tsx
src/renderer/redux/reducer.ts
src/renderer/utils/AddonData.ts

- requests the latest version names every 5 minutes
- checks for addon updates every 5 minutes (only if the state is UpToDate before, the latest update information is always verified by Fragmenter, this is only to make the update button appear)
- checks for installer updates every 5 minutes

feat: check for updates periodically

---

src/renderer/components/AircraftSection/index.tsx
src/renderer/data.ts

-Added new A32NX header image
-Reduced opacity to fit the image
Before: 
After: 
N/A
Discord username (if different from GitHub): GhostEagle68#0030

feat: Update a32nx header image

---

src/common/settings.ts
src/main/index.ts
src/renderer/actions/install-path.utils.tsx
src/renderer/components/AddonSection/index.tsx
src/renderer/components/SettingsSection/Download.tsx
src/renderer/utils/Directories.ts

Implements #375 
- Fixed `"Extension server error: Object not found: <top>"` error by loading the Developer Tools after the DOM is ready
- Added **tempPath** setting
- Added `defaultTempDir` function to determine the default temporary directory
- Added `setupTempPath` function to pick a temporary directory similar to picking the community directory
- After downloading an addon, the following function is run: `Directories.removeAllTemp();`, instead of `fs.removeSync(tempDir)`
- Added temporary path setting in "Downloads" tab in settings
- Changed the `temp` function in `Directories.ts` to get from setting
- Changed `removeAllTemp` to remove files inside set temporary directory
Before
After
Discord username: Marino#0001

feat: add customizable temp folder

---

src/common/settings.ts
src/renderer/components/AddonSection/StateSection.tsx
src/renderer/components/SettingsSection/Developer.tsx
src/renderer/components/SettingsSection/index.tsx
src/renderer/data.ts
src/renderer/index.tsx
src/renderer/redux/features/configuration.ts
src/renderer/utils/InstallerConfiguration.ts

The PR implements that the Installer fetches the configuration data from the FlyByWire CDN (fallback is still local config). 
The URL is configurable. 
See https://github.com/flybywiresim/installer-data/tree/staging

feat: cdn-based configuration

---

.github/CHANGELOG.yaml
package.json
src/common/settings.ts
src/renderer/actions/install-path.utils.tsx
src/renderer/components/AddonSection/MyInstall/index.tsx
src/renderer/components/AddonSection/StateSection.tsx
src/renderer/components/AddonSection/index.tsx
src/renderer/components/ErrorModal/index.tsx
src/renderer/components/LocalApiConfigEditUI/index.tsx
src/renderer/components/Modal/IncompatibleAddonDialog.tsx
src/renderer/components/Modal/index.css
src/renderer/components/SettingsSection/Download.tsx
src/renderer/data.ts
src/renderer/utils/AddonData.ts
src/renderer/utils/BackgroundServices.ts
src/renderer/utils/Directories.ts
src/renderer/utils/IncompatibleAddOnsCheck.ts
src/renderer/utils/InstallManager.tsx
src/renderer/utils/InstallerConfiguration.ts

This PR adds a configurable list of incompatible add-ons to each installable add-on. 
If searches the configured community folder and reads each folder/manifest.json to compare to the incompatibility list. 
Incompatible add-ons are listed in a warning with the recommendation to remove them. 
Example data only! List of incompatible add-ons is defined in installer-data repo. 
- Make sure to use this Installer config: https://cdn.flybywiresim.com/installer/config/pr-6.json (ask on Discord how to change)
- Configuration of Install folder and Community folder has been separated - test this as best possible
- See list of current known incompatible add-ons - install them an test Installer warning (sufficient to create a folder and place the add-on's manifest.json file in there).
Discord username …

feat: check and warning for installed incompatible add-ons

---

src/renderer/components/Modal/InstallSizeDialog.tsx
src/renderer/utils/FreeDiskSpace.ts
src/renderer/utils/InstallManager.tsx

* Free disk space check now takes symlinks into account
* Free disk space check now also verifies temporary directory
* Space is shown separately on modal if temporary directory is different than destination directory
*disregard WIP new addon UI - not part of PR*

fix: improve free disk space check

---

src/renderer/utils/Directories.ts

After the recent repo refactor, the final output of the A320 has moved further into the directory structure, meaning the `.git` folder is now 3 directories up instead of 1. This fixes it so the installer can once again detect git installs.

fix: git install detection

---

src/main/index.ts

This just adds support to allow CTRL + R to be used alongside CTRL F5 for reloading the installer window 
Discord username (if different from GitHub): alepouna

feat: Support for CTRL R for reloading

---

src/renderer/components/Modal/ErrorDialog.tsx
src/renderer/components/SentrySessionCard.tsx

Adds a button to copy an error message in the ErrorDialog to clipboard.
Also minor changes to text and text sizes.

feat: Error message to clipboard button

---

.github/CHANGELOG.yaml
package-lock.json
package.json
src/renderer/components/AddonSection/Configure/TrackSelector.tsx
src/renderer/components/AddonSection/ReleaseNotes/index.tsx
src/renderer/components/App/index.tsx
src/renderer/components/ErrorModal/index.tsx
src/renderer/components/InstallerUpdate/index.tsx
src/renderer/components/LocalApiConfigEditUI/index.tsx
src/renderer/components/Modal/ErrorDialog.tsx
src/renderer/components/Modal/index.tsx
src/renderer/components/SettingsSection/Developer.tsx
src/renderer/components/SettingsSection/Download.tsx
src/renderer/components/SettingsSection/General.tsx
src/renderer/components/Toggle.tsx
src/renderer/components/WindowActionButtons/index.tsx
src/renderer/fbw.scss
src/renderer/index.tsx

- Removed `antd` and `@ant-design/icons` and their remaining usages, to save about 8MB on the final exe size and be able to upload to CF again
- Fixes a potential leak with update state callbacks, clean up update state keeping

refactor: remove antd and antd icons

---

.github/CHANGELOG.yaml
src/main/index.ts

Fixes #465
Converts global Shortcuts/Keybinds to local keybinds so they do not hijack the keybind from other processes.

fix: Unhijack globalShortcut & convert to local

---

.github/CHANGELOG.yaml
src/renderer/data.ts

Updates the default installer data to the current latest data from https://github.com/flybywiresim/installer-data.
Note: If the installer loses internet connection, or invalid custom data are provided, the installer will default to this data, so it's good to keep the generally up 2 date. An automation (action?) in the future to fetch this data automatically would be ideal.

chore: Update default data

---

src/main/SentryClient.ts
src/main/index.ts
src/react-app-env.d.ts
src/renderer/components/App/NavBar.tsx
src/renderer/components/App/index.tsx
tsconfig.json

- Fix build differentiation between dev and prod

fix: dev/production build

---

package-lock.json
package.json
src/renderer/components/AddonSection/Configure/index.tsx
src/renderer/components/AddonSection/MyInstall/index.tsx
src/renderer/components/AddonSection/index.tsx
src/renderer/components/LocalApiConfigEditUI/index.tsx
src/renderer/data.ts
src/renderer/utils/Directories.ts
src/renderer/utils/InstallerConfiguration.ts

Needs https://github.com/flybywiresim/simbridge/pull/121 to be released first.

feat: read config json from documents dir

---

package.json

Since refactor: move to electron-vite for build, clean up CI (https://github.com/flybywiresim/installer/pull/462)
dev run script is no longer avalaible, 
this adds a script to run ``electron-vite dev`` and complies with current README instructions

build: add dev start script with electron-vite

---

src/renderer/components/SettingsSection/Developer.tsx

This adds a "Reset to default" button for the Configuration Download URL in the Developer Settings for developers convenience

feat: Add a "Reset to default" button for the Configuration Download URL (DeveloperSettings)

---

src/renderer/utils/InstallerConfiguration.ts

As it sometimes takes forever for users to see new configs we should make sure the config file is not cached. 
I tried with a http header which didn't work. So added a cache-killer parameter. 
https://discord.com/channels/738864299392630914/846470774361161808/1307387181605847120

fix: Avoid caching of config file

---

src/renderer/utils/IncompatibleAddOnsCheck.ts

- Error Handling for manifest.json Parsing:
Added a try-catch block to handle cases where `manifest.json` is invalid or unreadable.
Prevented the function from crashing due to syntax errors or unexpected tokens in manifest.json.
- Logging Improvements:
Implemented `console.warn` to log issues with specific `manifest.json` files for debugging purposes.
- Resilience Enhancements:
Ensured the function gracefully continues processing other directories even if a corrupt `manifest.json` is encountered.
These changes improve the reliability and robustness of the `checkIncompatibleAddOns` function.
Before:
After:

fix: handle invalid manifest.json files in checkIncompatibleAddOns function

---

src/renderer/components/SettingsSection/Developer.tsx

This update enhances the "Developer Settings" UI by introducing a new Reload Installer button for reloading the application and replacing the existing Reset to Default button with a styled Button component, ensuring a consistent and modern user experience. The changes also improve layout alignment and maintain existing functionality.
- **Reload Installer Button**:
- Introduced a new button using the `Button` component.
- Styled with `ButtonType.Neutral` and class attributes (`ml-2 h-fit min-h-10 text-lg`) for consistent UI.
- On click, sends the `ipcRenderer.send(channels.window.reload)` command to reload the installer.
- **Reset to Default Button**:
- Replaced the existing `<input type="button">` element with the `Button` component.
- Preserves functionality to reset …

refactor: enhance configuration url handle

---

README.md
src/renderer/data.ts

Updated default config data to reflect the new URLs for CF.
Removed incompatibleAddons sections as this should only be maintained in the installer-data repo. 

fix: updated default config data

---

src/renderer/components/SettingsSection/About.tsx

Updates the year in the Copyright text on the About page. 

chore: update copyright year
